### PR TITLE
Feature/list component

### PR DESCRIPTION
**Pull request by hd-darrenwhatford**

### CODE REVIEW

**Review by hdfeddanjackson — COMMENTED** [review]
The only thing missing from this component is a simple test.

**Comment by hd-darrenwhatford** [comment]
> The only thing missing from this component is a simple test.

Just looking at that now actually

**Review by hdfeddanjackson — COMMENTED** [review]
Just ran the test locally and it failed:

`TypeError: Cannot read property 'map' of undefined`

**Comment by hdfedscottquested** [comment]
> Just ran the test locally and it failed:
> 
> `TypeError: Cannot read property 'map' of undefined`

I think an array of key/values needs to be passed through the test

**Comment by hd-darrenwhatford** [comment]
> Just ran the test locally and it failed:
> 
> `TypeError: Cannot read property 'map' of undefined`

OK, thanks mate. One for me to look at tomorrow now I think - with a fresh brain!

**Comment by hdfeddanjackson** [comment]
> > Just ran the test locally and it failed:
> > `TypeError: Cannot read property 'map' of undefined`
> 
> I think an array of key/values needs to be passed through the test

I think you're correct, looks like that could be the issue, the list has nothing to output.

**Pull request merged**
